### ISSUE TITLE
无法build

### ISSUE THREAD

**Issue by taolive** [smallcatcat-joe/webpack-esnext-cli#6]
输入：npm run build:prod 
提示：
11 info lifecycle webpack-exnext-cli@0.0.1~prebuild:prod: Failed to exec prebuild:prod script
12 verbose stack Error: webpack-exnext-cli@0.0.1 prebuild:prod: `sh bin/clean-public.sh`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (D:\idea\nodejs_wk\node_gobal\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
12 verbose stack     at EventEmitter.emit (events.js:182:13)
12 verbose stack     at ChildProcess.<anonymous> (D:\idea\nodejs_wk\node_gobal\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:957:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)

npm run dev 是正常的

**Comment by taolive** [comment]
原来是不兼容windows机器，删掉
 "prebuild:test": "sh bin/clean-public.sh",
    "prebuild:prod": "sh bin/clean-public.sh",

两行代码就好了
